name: Build and Deploy
on:
  push:
    branches: [ main ] # Only run on pushes to the main branch
    paths-ignore:
      - '.github/**'

jobs:
  build:
    if: github.actor == 'github-actions[bot]' || github.actor != 'github-actions[bot]'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ghcr.io/nathanrazaf/that-game-tools-api:latest